spring:
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
server:
  port: 6700
  servlet:
    context-path: /auth
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: azPUJhTO1EVONnA91nwmOCkh1Pf2JRyY
    realm: spring
    serverUrl: http://localhost:8080

log:
  level: debug
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
